
version: 2

sources:
  - name: atomic
    schema: "{{ var('atomic_schema', 'atomic') }}"
    tables:
      - name: events
        identifier: "{{ var('events_table', 'events') }}"
  - name: derived
    schema: "{{ var('page_views_schema', 'derived') }}"
    tables:
      - name: snowplow_web_page_views
        identifier: "{{ var('page_views_table', 'snowplow_web_page_views') }}"
        
models:
  - name: channel_counts
    description: Number of conversion events per channel, campaign, source and medium
    columns:
      - name: channel
        description: Channel name
      - name: campaign
        description: Campaign name
      - name: source
        description: Source / referring host
      - name: medium
        description: Marketing medium
      - name: number_of_events
        description: Count of events per channel / campaign / source / medium

  - name: conversions_by_customer_id
    description: Each conversion and associated revenue per customer_id
    columns:
      - name: customerId
        description: Identifier for the customer, 'f' prefixed when domain_userid is used, 'u' prefixed for when user_id is used (logged in?)
      - name: conversionTimestamp
        description: UTC timestamp for the conversion
      - name: revenue
        description: Revenue (dollars / cents) for the conversion
      

  - name: path_summary
    description: For each unique path, a summary of associated conversions, non conversions and revenue
    columns:
      - name: transformedPath
        description: "> delimited path summary"
      - name: conversions
        description: Count of conversions for this path
      - name: nonConversions
        description: Count of non-conversions for path
      - name: revenue
        description: Revenue for the given path
      - name: direct_display_other_organic_search_paid_search_referral
        description: These columns may be created dynamically... 

  - name: paths_to_conversion
    description: Customer id and the the paths the customer has followed that have lead to conversion
    columns:
      - name: customerId
        description: Id for the customer (identified or cookie)
      - name: conversionTimestamp
        description: UTC timestamp for the conversion event
      - name: revenue
        description: Revenue associated with the conversion
      - name: path
        description: Path to conversion (> delimited)
      - name: transformedPath
        description: Transformations applied to "path" above

  - name: paths_to_non_conversion
    description: Customer id and the the paths the customer has followed that have not lead to conversion
    columns:
      - name: customerId
        description: Id for the customer (identified or cookie)
      - name: path
        description: Path to conversion (> delimited)
      - name: transformedPath
        description: Transformations applied to "path" above

  - name: sessions_by_customer_id
    description: >
      Channels per session by customer id, yields one row per session unless consider_intrasession_channels is true
    columns:
      - name: customerId
        description: Customer id
      - name: visitStartTimestamp
        description: UTC timestamp for the start of the session
      - name: channel
        description: Channel
      - name: referralPath
        description: Referall path for the session
      - name: campaign
        description: Marketing campaign
      - name: source
        description: Marketing source
      - name: medium
        description: Marketing medium
      