name: 'snowplow_fractribution_integration_tests'
version: '0.2.0'
config-version: 2

profile: 'integration_tests'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "dbt_packages"

quoting:
  identifier: false
  schema: false

models:
  snowplow_fractribution_integration_tests:
    bind: false
    +schema: "snplw_fractribution_int_tests"
    source:
      bigquery:
        +enabled: "{{ target.type == 'bigquery' | as_bool() }}"
      databricks:
        +enabled: "{{ target.type in ['databricks', 'spark'] | as_bool() }}"
      snowflake:
        +enabled: "{{ target.type == 'snowflake' | as_bool() }}"
  snowplow_web:
    sessions:
      enabled: false
    user_mapping:
      enabled: false
    users:
      enabled: false

vars:
  snowplow__enable_custom_example: false
  snowplow_web:
    snowplow__events: "{{ ref('snowplow_fractribution_events_stg') }}"
    snowplow__start_date: '2022-06-03'
    snowplow__databricks_catalog: 'atomic'
    snowplow__backfill_limit_days: 60

  snowplow_fractribution:
    snowplow__conversion_window_start_date: '2022-06-03'
    snowplow__conversion_window_end_date: '2022-08-01'
    snowplow__conversion_hosts: ['poplindata.com']
    snowplow__path_lookback_steps: 0
    snowplow__path_lookback_days: 30
    snowplow__path_transforms:  {'exposure_path': null}
    snowplow__consider_intrasession_channels: false
    snowplow__page_views_source: '{{target.schema}}_derived.snowplow_web_page_views'
    snowplow__conversions_source: "{{ ref('snowplow_fractribution_events_stg') }}"

seeds:
  quote_columns: false
  snowplow_fractribution_integration_tests:
    +schema: "snplw_fractribution_int_tests"
    source:
      snowplow_fractribution_events:
        +column_types:
          app_id: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          platform: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          etl_tstamp: timestamp
          collector_tstamp: timestamp
          dvce_created_tstamp: timestamp
          event: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          event_id: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          txn_id: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          name_tracker: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          v_tracker: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          v_collector: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          v_etl: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          user_id: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          user_ip_address: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          domain_userid: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          domain_sessionidx: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          network_userid: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          geo_country: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          geo_region: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          geo_city: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          geo_zipcode: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          geo_latitude: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          geo_longitude: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          geo_region_name: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          page_url: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          page_title: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          page_referrer: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          page_urlscheme: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          page_urlhost: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          page_urlport: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          page_urlpath: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          page_urlquery: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          refr_urlscheme: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          refr_urlhost: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          refr_urlport: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          refr_urlpath: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          refr_urlquery: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          mkt_medium: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          mkt_source: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          mkt_campaign: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          se_category: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          se_action: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          ti_quantity: float
          pp_xoffset_min: float
          pp_xoffset_max: float
          pp_yoffset_min: float
          pp_yoffset_max: float
          useragent: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          br_lang: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          br_features_pdf: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          br_features_flash: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          br_features_java: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          br_features_director: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          br_features_quicktime: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          br_features_realplayer: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          br_features_windowsmedia: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          br_features_gears: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          br_features_silverlight: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          br_cookies: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          br_viewwidth: float
          br_viewheight: float
          os_timezone: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          dvce_screenwidth: float
          dvce_screenheight: float
          doc_charset: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          doc_width: float
          doc_height: float
          geo_timezone: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          mkt_clickid: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          mkt_network: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          domain_sessionid: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          event_vendor: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          event_name: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          event_format: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          event_version: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          event_fingerprint: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          user_fingerprint: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          ip_isp: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          ip_organization: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          ip_domain: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          ip_netspeed: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          page_urlfragment: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          refr_urlfragment: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          refr_medium: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          refr_source: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          refr_term: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          mkt_term: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          mkt_content: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          se_label: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          se_property: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          se_value: float
          tr_orderid: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          tr_affiliation: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          tr_total: "{{ 'float' if target.type in ['bigquery'] else 'decimal(10,2)' }}"
          tr_tax: float
          tr_shipping: float
          tr_city: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          tr_state: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          tr_country: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          ti_orderid: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          ti_sku: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          ti_name: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          ti_category: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          ti_price: float
          br_name: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          br_family: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          br_version: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          br_type: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          br_renderengine: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          br_colordepth: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          os_name: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          os_family: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          os_manufacturer: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          dvce_type: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          dvce_ismobile: boolean
          tr_currency: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          tr_total_base: float
          tr_tax_base: float
          tr_shipping_base: float
          ti_currency: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          ti_price_base: float
          base_currency: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          etl_tags: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          dvce_sent_tstamp: timestamp
          refr_domain_userid: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
          refr_dvce_tstamp: timestamp
          derived_tstamp: timestamp
          true_tstamp: timestamp
          load_tstamp: timestamp

    expected:
      snowplow_fractribution_channel_counts_expected:
        channel: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
        campaign: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
        source: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
        medium: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
        number_of_sessions: float
      snowplow_fractribution_channel_spend_expected:
        channel: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
        spend: float
      snowplow_fractribution_conversions_by_customer_id_expected:
        customer_id: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
        conversion_tstamp: timestamp
        revenue: float
      snowplow_fractribution_path_summary_expected:
        transformed_path: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
        conversions: float
        non_conversions: float
        revenue: float
      snowplow_fractribution_paths_to_conversion_expected:
        customer_id: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
        conversion_tstamp: timestamp
        revenue: float
        path: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
        transformed_path: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
      snowplow_fractribution_paths_to_non_conversion_expected:
        customer_id: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
        path: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
        transformed_path: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
      snowplow_fractribution_sessions_by_customer_id_expected:
        customer_id: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
        visit_start_tstamp: timestamp
        channel: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
        referral_path: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
        campaign: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
        source: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
        medium: "{{ 'string' if target.type in ['bigquery', 'databricks', 'spark'] else 'varchar' }}"
