version: 2

macros:
  - name: channel_classification
    description: A macro used to perform channel classifications

  - name: channel_spend
    description: A macro for the user to overwrite it with a sql script to extract total ad spend by channel

  - name: conversion_clause
    description: A macro to specify how to filter on conversion events

  - name: conversion_value
    description: A macro that specifies either a single column or a calculated value that represents the value associated with the conversion

  - name: create_udfs
    description: A macro which creates user defined functions that will be used in the models
