name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build_container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get package version
        id: version
        # Grab the version number of from the project.yml file as the pushed version of the package, set to variable dbt_package_version
        run: |
          echo "dbt_package_version=$(grep -oP "(?<=version: ')(.*)(?=')" dbt_project.yml)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./utils
          file: ./utils/Dockerfile
          push: true
          tags: |
            snowplow/fractribution:${{steps.version.outputs.dbt_package_version}}
            snowplow/fractribution:latest
